import { randomBytes } from 'node:crypto'
import { link, mkdir, open, readFile, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import { sha256, verifyReceipt } from './receipt.js'
import type { GitChangedFile, Receipt, ToolReceipt } from './types.js'

function markdownText(value: unknown): string {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, '<br>')
}

function codeFence(value: string): string {
  const runs = value.match(/`+/g) ?? []
  const width = Math.max(3, ...runs.map(run => run.length + 1))
  const fence = '`'.repeat(width)
  return `${fence}text\n${value}\n${fence}`
}

function optionalNumber(value: number | undefined): string {
  return value === undefined ? '—' : value.toLocaleString('en-US')
}

function renderTool(tool: ToolReceipt, index: number): string {
  const lines = [
    `### Tool ${index + 1}`,
    '',
    '| Field | Value |',
    '|---|---|',
    `| Name | ${markdownText(tool.name)} |`,
    `| Call | ${markdownText(tool.callRef)} |`,
    `| Transport | ${markdownText(tool.transport)} |`,
    `| Status | ${markdownText(tool.status)} |`,
    `| Started | ${markdownText(tool.startedAt)} |`,
    `| Observed elapsed | ${tool.durationMs === undefined ? '—' : `${tool.durationMs} ms`} |`,
    `| Timing source | ${markdownText(tool.timingSource ?? '—')} |`,
  ]
  if (tool.execution !== undefined) {
    lines.push(`| Exit code | ${tool.execution.exitCode === undefined ? '—' : markdownText(tool.execution.exitCode)} |`)
    lines.push(`| Signal | ${tool.execution.signal === undefined ? '—' : markdownText(tool.execution.signal)} |`)
    lines.push(`| Timed out | ${tool.execution.timedOut === undefined ? '—' : markdownText(tool.execution.timedOut)} |`)
    lines.push(`| Execution facts | ${tool.execution.inferred === true ? 'inferred from durable shell marker' : 'live observation'} |`)
  }
  if (tool.error !== undefined) {
    lines.push(`| Error | ${markdownText([tool.error.name, tool.error.code].filter(Boolean).join(' / ') || 'unspecified')} |`)
  }
  lines.push(`| Argument keys | ${tool.arguments.keys.length === 0 ? '—' : markdownText(tool.arguments.keys.join(', '))} |`)
  if (tool.output !== undefined) {
    lines.push(`| Output summary | ${tool.output.bytes.toLocaleString('en-US')} bytes / ${tool.output.blocks} block(s) |`)
  }
  if (tool.arguments.command !== undefined) {
    lines.push('', '**Redacted command**', '', codeFence(tool.arguments.command))
  }
  if (tool.output?.preview !== undefined) {
    lines.push('', '**Redacted output preview**', '', codeFence(tool.output.preview))
  }
  return lines.join('\n')
}

function renderChangedFile(file: GitChangedFile): string {
  const changes = file.binary === true
    ? 'binary'
    : file.additions === undefined && file.deletions === undefined
      ? '—'
      : `+${file.additions ?? 0} / -${file.deletions ?? 0}`
  const hash = file.worktreeSha256 ?? file.hashState ?? '—'
  return `| ${markdownText(file.status)} | ${markdownText(file.path)} | ${markdownText(changes)} | ${markdownText(hash)} |`
}

export function renderReceiptMarkdown(receipt: Receipt): string {
  const lines = [
    '# DSH Receipt',
    '',
    '> Local execution evidence generated by `dsh-receipt`. JSON is the authoritative artifact.',
    '',
    '## Summary',
    '',
    '| Field | Value |',
    '|---|---|',
    `| Producer | ${markdownText(`${receipt.producer.name}@${receipt.producer.version}`)} |`,
    `| Tested DSH | ${markdownText(receipt.producer.testedHarnessVersion)} |`,
    `| Receipt | ${markdownText(receipt.receiptId)} |`,
    `| Session | ${markdownText(receipt.session.ref)} |`,
    `| Turn | ${receipt.turn.number} |`,
    `| Status | ${markdownText(receipt.turn.status)} |`,
    `| Reason | ${markdownText(receipt.turn.reason)} |`,
    `| Started | ${markdownText(receipt.turn.startedAt)} |`,
    `| Ended | ${markdownText(receipt.turn.endedAt)} |`,
    `| Duration | ${receipt.turn.durationMs} ms |`,
  ]
  if (receipt.session.cwd !== undefined) lines.push(`| Working directory | ${markdownText(receipt.session.cwd)} |`)
  if (receipt.session.parentRef !== undefined) lines.push(`| Parent session | ${markdownText(receipt.session.parentRef)} |`)
  if (receipt.turn.failure !== undefined) {
    lines.push(`| Failure | ${markdownText(receipt.turn.failure.message)} |`)
  }

  lines.push('', '## Model and usage', '')
  if (receipt.models.length === 0) lines.push('No model request was observed in this turn.')
  else {
    lines.push('| Provider | Model | Reasoning |', '|---|---|---|')
    for (const model of receipt.models) {
      lines.push(`| ${markdownText(model.provider)} | ${markdownText(model.model)} | ${markdownText(model.reasoningEffort ?? '—')} |`)
    }
  }
  if (receipt.usage !== undefined) {
    lines.push(
      '',
      '| Input | Output | Cache read | Cache write | Reasoning |',
      '|---:|---:|---:|---:|---:|',
      `| ${optionalNumber(receipt.usage.inputTokens)} | ${optionalNumber(receipt.usage.outputTokens)} | ${optionalNumber(receipt.usage.cacheReadTokens)} | ${optionalNumber(receipt.usage.cacheWriteTokens)} | ${optionalNumber(receipt.usage.reasoningTokens)} |`,
      '',
      '_Reasoning tokens are a subset of output tokens, not an additional bucket._',
    )
  }

  lines.push('', '## Tools', '')
  if (receipt.tools.length === 0) lines.push('No tool calls were observed.')
  else lines.push(receipt.tools.map(renderTool).join('\n\n'))

  lines.push('', '## Approvals', '')
  if (receipt.approvals.length === 0) lines.push('No approval audit events were observed.')
  else {
    lines.push('| Approval | Tool | Outcome |', '|---|---|---|')
    for (const approval of receipt.approvals) {
      lines.push(`| ${markdownText(approval.ref)} | ${markdownText(approval.toolName ?? '—')} | ${markdownText(approval.outcome ?? 'pending')} |`)
    }
  }

  lines.push('', '## Git evidence', '')
  if (!receipt.git.available) {
    lines.push(`Unavailable: ${markdownText(receipt.git.reason)}${receipt.git.message === undefined ? '' : ` — ${markdownText(receipt.git.message)}`}`)
  } else {
    lines.push(
      `- Scope: ${markdownText(receipt.git.scope)}`,
      `- Repository: ${markdownText(receipt.git.repositoryRoot)}`,
      `- Branch: ${markdownText(receipt.git.branch ?? '(detached)')}`,
      `- HEAD: ${markdownText(receipt.git.head ?? '(unborn)')}`,
      `- Dirty: ${receipt.git.dirty ? 'yes' : 'no'}`,
      `- Diff: ${receipt.git.diff.files} file(s), +${receipt.git.diff.additions}, -${receipt.git.diff.deletions}, ${receipt.git.diff.binaryFiles} binary`,
      '',
    )
    if (receipt.git.changedFiles.length === 0) lines.push('No changed paths were reported.')
    else {
      lines.push('| Status | Path | Changes | Worktree SHA-256 / state |', '|---|---|---:|---|')
      lines.push(...receipt.git.changedFiles.map(renderChangedFile))
      if (receipt.git.changedFilesTruncated) lines.push('', '_Changed path list truncated by configuration._')
    }
    if (receipt.git.warnings.length > 0) {
      lines.push('', '**Warnings**', '', ...receipt.git.warnings.map(warning => `- ${markdownText(warning)}`))
    }
  }

  lines.push(
    '',
    '## Verification boundaries',
    '',
    ...receipt.verification.limitations.map(limitation => `- ${markdownText(limitation)}`),
    '',
    `Tool result coverage: ${receipt.verification.observedToolResults}/${receipt.verification.observedToolCalls}; failed tools: ${receipt.verification.failedTools}.`,
    '',
    '## Redaction and integrity',
    '',
    `Redactions: ${receipt.redaction.total}${receipt.redaction.total === 0 ? '' : ` (${Object.entries(receipt.redaction.byKind).map(([kind, count]) => `${kind}: ${count}`).join(', ')})`}.`,
    '',
    `Payload digest (${receipt.integrity.algorithm}, ${receipt.integrity.canonicalization}):`,
    '',
    codeFence(receipt.integrity.digest),
    '',
  )
  return lines.join('\n')
}

export function safeSessionDirectory(sessionId: string): string {
  return `session-${sha256(sessionId).slice(0, 16)}`
}

async function atomicCreate(path: string, content: string): Promise<void> {
  const temporary = `${path}.${process.pid}.${randomBytes(8).toString('hex')}.tmp`
  let handle: Awaited<ReturnType<typeof open>> | undefined
  try {
    handle = await open(temporary, 'wx', 0o600)
    await handle.writeFile(content, 'utf8')
    await handle.sync()
    await handle.close()
    handle = undefined
    // Hard-linking the fully synced temp file is an atomic, no-clobber commit in the same directory.
    await link(temporary, path)
    await unlink(temporary)
  } catch (error) {
    await handle?.close().catch(() => undefined)
    await unlink(temporary).catch(() => undefined)
    throw error
  }
}

async function existingReceiptDigest(path: string): Promise<string | undefined> {
  try {
    const parsed = JSON.parse(await readFile(path, 'utf8')) as Receipt
    if (!verifyReceipt(parsed)) throw new Error('integrity verification failed')
    return parsed.integrity.digest
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw new Error(`dsh-receipt: existing receipt is unreadable or invalid: ${path}`, { cause: error })
  }
}

async function existingText(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

export interface WrittenReceipt {
  directory: string
  jsonPath: string
  markdownPath: string
}

export async function writeReceipt(
  receipt: Receipt,
  outputDir: string,
  rawSessionId: string,
): Promise<WrittenReceipt> {
  if (!verifyReceipt(receipt)) throw new Error('dsh-receipt: refusing to write a receipt with an invalid integrity digest')
  const turnDirectory = `turn-${String(receipt.turn.number).padStart(6, '0')}`
  const directory = join(outputDir, safeSessionDirectory(rawSessionId), turnDirectory)
  await mkdir(directory, { recursive: true, mode: 0o700 })
  const jsonPath = join(directory, 'receipt.json')
  const markdownPath = join(directory, 'receipt.md')
  const markdown = renderReceiptMarkdown(receipt)
  const json = `${JSON.stringify(receipt, null, 2)}\n`

  const existingDigest = await existingReceiptDigest(jsonPath)
  if (existingDigest !== undefined && existingDigest !== receipt.integrity.digest) {
    throw new Error(`dsh-receipt: refusing to overwrite a conflicting receipt at ${jsonPath}`)
  }
  if (existingDigest === undefined) {
    try {
      await atomicCreate(jsonPath, json)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error
      const racedDigest = await existingReceiptDigest(jsonPath)
      if (racedDigest !== receipt.integrity.digest) {
        throw new Error(`dsh-receipt: refusing to overwrite a conflicting receipt at ${jsonPath}`)
      }
    }
  }
  // JSON is the commit point. A later identical run can rebuild a missing Markdown projection.
  const existingMarkdown = await existingText(markdownPath)
  if (existingMarkdown === undefined) {
    try {
      await atomicCreate(markdownPath, markdown)
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error
      if (await existingText(markdownPath) !== markdown) {
        throw new Error(`dsh-receipt: refusing to accept a conflicting Markdown projection at ${markdownPath}`)
      }
    }
  } else if (existingMarkdown !== markdown) {
    throw new Error(`dsh-receipt: refusing to accept a conflicting Markdown projection at ${markdownPath}`)
  }
  return { directory, jsonPath, markdownPath }
}
